/*
 * Copyright 2026 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.google.ai.edge.gallery.rag

/*
 * Shared Phase 3 (RAG) data contracts.
 *
 * These are the stable shapes the RAG pipeline (Dev A/C) produces and the
 * Quiz/Flashcard UI (Dev B) consumes. Per /docs/WORKSTREAM.md the backend
 * defines this interface first, before UI is built against it — so keep these
 * shapes additive: add nullable/defaulted fields rather than breaking existing
 * ones once the UI has started consuming them.
 *
 * Everything here is on-device only; no field crosses a network boundary.
 */

/**
 * One chunk of an ingested note/document.
 *
 * Source text is split into passages during ingestion, each embedded once and
 * held in the in-memory vector store for the session. [sourceLabel] is a
 * human-readable origin (e.g. a file display name) shown in the UI so a
 * retrieved answer can be traced back to the note it came from.
 */
data class NoteChunk(
  val id: String,
  val text: String,
  val sourceLabel: String,
  /** Position of this chunk within its source document (0-based), for ordering/citation. */
  val ordinal: Int = 0,
)

/** A [NoteChunk] paired with its embedding vector. Internal to the store/pipeline. */
data class EmbeddedChunk(
  val chunk: NoteChunk,
  val embedding: FloatArray,
) {
  // data class equals/hashCode don't handle FloatArray by value; override so
  // dedup/set operations behave. Identity is the chunk id — embeddings for the
  // same id are considered equal.
  override fun equals(other: Any?): Boolean {
    if (this === other) return true
    if (other !is EmbeddedChunk) return false
    return chunk.id == other.chunk.id
  }

  override fun hashCode(): Int = chunk.id.hashCode()
}

/** A retrieved chunk plus its similarity score, ordered most-relevant first. */
data class RetrievalResult(
  val chunk: NoteChunk,
  /** Cosine similarity in [-1, 1]; higher is closer. */
  val score: Float,
)

/**
 * A citation shown to the user: which note a generated answer drew from, with
 * the actual passage as proof. Built deterministically from the retrieval
 * results (not from model output), so it can't be hallucinated.
 */
data class Citation(
  val sourceLabel: String,
  /** The retrieved passage (may be truncated for display). */
  val snippet: String,
  /** Retrieval similarity score in [-1, 1]. */
  val score: Float,
)

/**
 * A single quiz/flashcard item generated by Gemma, grounded in retrieved notes.
 *
 * The UI renders [question], reveals [answer], and (for multiple-choice) shows
 * [options] with [answer] as the correct one. For plain flashcards, [options]
 * is empty and the card simply flips question -> answer.
 *
 * [sourceLabel] is the note the item was grounded in, surfaced in the UI so the
 * user can trust the item came from their own content, not general knowledge.
 */
data class QuizItem(
  val question: String,
  val answer: String,
  /** Multiple-choice options including the correct [answer]; empty = flashcard mode. */
  val options: List<String> = emptyList(),
  val sourceLabel: String = "",
) {
  val isMultipleChoice: Boolean
    get() = options.isNotEmpty()
}

/**
 * Result of a RAG generation request the UI renders.
 *
 * Exactly one generation produces either a quiz ([items] non-empty) or a plain
 * [summary] string, depending on what the user asked for. [sources] lists the
 * note labels that were actually retrieved and fed to the model, so the UI can
 * show "based on: <notes>" and prove grounding. [citations] carries the exact
 * retrieved passages behind the answer, for a per-response citation list.
 */
data class RagResponse(
  val items: List<QuizItem> = emptyList(),
  val summary: String = "",
  val sources: List<String> = emptyList(),
  val citations: List<Citation> = emptyList(),
) {
  val isQuiz: Boolean
    get() = items.isNotEmpty()
}
